### ISSUE TITLE
support getters and setters

### ISSUE THREAD

**Issue by rhelmer** [erikrose/sphinx-js#10]
I can't figure out how to get at setters and getters in `sphinx-js`. Sample code:

```
class Foo {
  constructor() {
    this.baz = undefined;
  }
  get bar() {
    return this.baz;
  }
  set bar(baz) {
    this.baz = baz;
  }
}
```

**Comment by erikrose** [comment]
How would you like the docs to look?

**Comment by rhelmer** [comment]
It might be enough to just show them as members... I'm not sure it's necessary to expose in the documentation that they are actually getters/setters and not just regular JS properties, so I think it's an implementation detail as far as the client knows (AFAIK, I could be wrong about what people expect here).

I think that'd be enough for now and the documenter could put in more information in what the getter or setter is actually doing.

**Comment by erikrose** [comment]
Okay, so it should spit out the same stuff as autoattr.

**Comment by erikrose** [comment]
Actually, nm, they should not look like an attr, because then where would we show both docstrings if the getter and setter each have one? We'll need to show then separately, probably looking like "get foo" and "set foo". So the real question is how to refer to them in the autofunction directive. And what to do if you just want to document it as a simple attr, pulling in a docstring from somewhere or other.

**Comment by rhelmer** [comment]
Hm, so I searched around about this and I think the consensus from jsdoc folks is that you should just document one of them:

https://github.com/jsdoc3/jsdoc/issues/973#issuecomment-90274714

I think this makes sense... a setter/getter is the same to the caller as a single property (which you can set or get), it's just that there can be logic hidden behind the scenes. Having separate `set foo` and `get foo` doesn't really matter to the caller.

I guess *technically* a same-named setter+getter could take and return different types, but I don't think that's at all what the feature is intended for - it's supposed to be sugar over accessor methods, to make them look like plain ol' properties.

**Comment by rhelmer** [comment]
So to annotate this with jsdoc, the input would look like:

```
/**
   * For all for foo needs.
   */
class Foo {
  constructor() {
    this.baz = undefined;
  }
  /**
     * @type {string}
     */
  get bar() {
    return this.baz;
  }
  set bar(baz) {
    this.baz = baz;
  }
}
```

The sphinx docs should show a single `member` of type `string`.

**Comment by erikrose** [comment]
Okay. So, from the sphinx-js side, I think the safest and easiest thing to do is to…

1. Act as if the name of the getter and setter are both "Foo.bar". Conveniently and corroboratively, this is also what JSDoc itself thinks: it lists "Foo#bar" for both the getter's and the setter's `longname` in its `-X` output.
2. Naturally let the last encountered documented one win. If you document only one, then that one of course wins. The current code already does this.

Falling out from that, `:members:`, once implemented, will show a single property for a getter/setter pair.

**Comment by erikrose** [comment]
Whaddaya know? Code already does everything you need. Witness c39f999. The trick is to document them as attributes rather than functions.
