### ISSUE TITLE
Don't immediately error on path already in suffix tree

### ISSUE THREAD

**Issue by xmo-odoo** [erikrose/sphinx-js#17]
I'm currently in the process of trying to add JS documentation to an existing Python/Sphinx doc, and sphinx-js is basically my one hope.

The JS side is already kinda-sorta documented but fuzzy/informal and not actually correct: while JsDoc tags are used it's often incorrectly and many of the most "structuring" ones (`class`, `lends`, `extends`, …) are missing entirely which obviously generates an incorrect structure.

However sphinx-js currently bails at any conflicting structure e.g. two different types (the project is still ES5 and using an object-based "class system") declaring the same method will yield a conflicting function definition, which will stop sphinx-js immediately.

It would be nice if sphinx-js logged a conflict error but kept going, and only notified a build failure at the very end. That way one could easily get a complete "corpus" of problematic files and structures.

**Comment by erikrose** [comment]
Do you mean you're getting a `PathTaken` error, e.g. "Attempted to add a path already in the suffix tree: blah"? I'd love to see a small example of what's causing this in the real world for you. I'll have to look at what facilities are available in Sphinx for error handling, but maybe we can make it non-fatal if it makes sense. Thanks for being an early user!

**Comment by xmo-odoo** [comment]
> Do you mean you're getting a PathTaken error, e.g. "Attempted to add a path already in the suffix tree: blah"?

Yeah. It's great to have an error report of this (it *is* usually a mistake) but getting it eagerly is annoying when it's a very very common defect.

> I'd love to see a small example of what's causing this in the real world for you. 

Using John Resig's [simple javascript inheritance](https://johnresig.com/blog/simple-javascript-inheritance/) system in an ES5 codebase, 
```javascript
var Person = Class.extend({
  init: function(){},
});
var Ninja = Person.extend({
    init: function(){},
});
```
Before annotations (or with incomplete annotations) JsDoc will not understand the classes and will see two functions with the same namepath (and thus conflicting in the sphinx-js suffix tree).

This is not an issue in small codebases, but I'm dealing with 250kLOC of barely or incompletely annotated JS so it comes up frequently.

> maybe we can make it non-fatal if it makes sense.

I think it should very much remain fatal (it *is* an error and will yield incorrect documentation), just deferred, maybe printed immediately and failing once all the tree has been processed so the user can get feedback without having to run jsdoc then recompile their doc for every single problem.

> Thanks for being an early user!

Sadly I couldn't coerce JsDoc into yielding proper/usable structures, so more like a tester, I ultimately have to NIH it.

**Comment by erikrose** [comment]
Thanks for the good example, and sorry for my late reply. GitHub did not see fit to send me a mail for some reason. I should be able to get that patched up for you pretty easily.

**Comment by erikrose** [comment]
Sorry you couldn't get JSDoc to digest what you're doing. Do let me know what you end up putting together, though.

**Comment by xmo-odoo** [comment]
> Do let me know what you end up putting together, though.

A custom extractor (we've got a pretty strict structure internally so I can infer classes & al from the specific accesses/calls) based around PiotrDabkowski/pyjsparser (patched to extract comments instead of discarding them, don't know if the author has built a release for that yet) and nostrademons/pyjsdoc (pretty extensively monkeypatched as the original is opinionated with different opinions than what we need, but the parser itself works fine).

It's really specific to our code structure though, not a general-purpose docstring extractor.

I haven't yet started on the sphinx integration but in the context of #18 I was thinking maybe the "doclet" extractor could be pluggable in sphinx-js and anything able to produce the specified format would be an acceptable input to the rest of the processing?

**Comment by erikrose** [comment]
It would certainly be cheap to make it pluggable. We could use setuptools entry points and/or config options. Do you think the JSDoc doclet format is sufficiently flexible to use as a target for other extractors?

**Comment by xmo-odoo** [comment]
I still have yet to look into it, so I have absolutely no idea at this point.
