### ISSUE TITLE
"make html" error: cannot import name python_2_unicode_compatible

### ISSUE THREAD

**Issue by dmose** [erikrose/sphinx-js#32]
Running `make html` on MacOS Sierra, 10.12.6, using python 2.7.10 installed by homebrew yields:

`Could not import extension sphinx_js (exception: cannot import name python_2_unicode_compatible)`

**Comment by erikrose** [comment]
Try doing `pip install --upgrade six`. I think python_2_unicode_compatible was introduced in a new-ish version, and I don't have the requirements pinned down very tightly.

**Comment by erikrose** [comment]
You'll need 1.9.0 or better, as it turns out. Thanks for pointing this out!
