### ISSUE TITLE
HTML showing in output

### ISSUE THREAD

**Issue by jthomerson** [erikrose/sphinx-js#36]
I'm trying to add Sphinx and sphinx-js to a project where we already have extensive JSDoc documentation. I've followed the tutorial in your README and it works, except that the documentation it's rendering the escaped HTML that it is pulling in from JSDoc. Here's an example of what I mean:

This JS block appears in my code:

```js
   /**
    * Plays or resumes playing the currently selected item.
    *
    * Does nothing if no playlist has been set or if the player's playlist has not been
    * loaded.
    *
    * @param [seekToTime] {number} The time to seek to in seconds
    * @returns {BaseMediaPlayer} `this` for chaining
    * @fires BaseMediaPlayer#itemPlaying
    * @fires BaseMediaPlayer#seekStarted
    * @fires BaseMediaPlayer#seeking
    * @fires BaseMediaPlayer#seekEnded
    */
```

This appears in my `index.rst`:

```rst
.. js:autofunction:: VideoPlayer#play
```

And this is how it renders:

![image](https://user-images.githubusercontent.com/171934/33996586-a75c9dee-e0af-11e7-8891-80ecd3d7079e.png)

Here is my `conf.py` file ... it is the default file created by the quickstart, with the addition of the config for sphinx-js and the RTD theme (although I confirmed that it happens with the default alabaster theme as well).

```py
extensions = ['sphinx_js']
js_source_path = '../src'
jsdoc_config_path = '../.jsdoc.json'
primary_domain = 'js'
templates_path = ['_templates']
source_suffix = '.rst'
master_doc = 'index'
project = u'Media Player'
copyright = u'2017, Dev Team'
author = u'Dev Team'
version = u'0.9'
release = u'0.9.0'
language = None
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
pygments_style = 'sphinx'
todo_include_todos = False
html_theme = "sphinx_rtd_theme"
html_static_path = ['_static']
html_sidebars = {
    '**': [
        'relations.html',  # needs 'show_related': True theme option to display
        'searchbox.html',
    ]
}

htmlhelp_basename = 'MediaPlayerdoc'

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

latex_documents = [
    (master_doc, 'MediaPlayer.tex', u'Media Player Documentation',
     u'Dev Team', 'manual'),
]

man_pages = [
    (master_doc, 'mediaplayer', u'Media Player Documentation',
     [author], 1)
]

texinfo_documents = [
    (master_doc, 'MediaPlayer', u'Media Player Documentation',
     author, 'MediaPlayer', 'One line description of project.',
     'Miscellaneous'),
]
```

Sorry, I'm completely new to Sphinx and Sphinx JS, so it may be something simple I'm missing.

**Comment by erikrose** [comment]
I tried a build using your comment and your conf file, and I don't see the escaped tags you see. I also tried updating to the latest version of Sphinx (I was at 1.6.3, and 1.6.5 is now out). Maybe try that (`pip install -U Sphinx`) and see if it helps?

**Comment by jthomerson** [comment]
Hmmm... that's odd. I'm also at 1.6.5. Here's a tarball that contains a slimmed down repo that shows the problem. I included the output of my build in it so you can compare.

```
tar xzf sphinx-js-sample.tar.gz
cd sphinx-js-sample
npm install # not sure if you'll need this or not
cd docs
make html
```
[sphinx-js-sample.tar.gz](https://github.com/erikrose/sphinx-js/files/1563607/sphinx-js-sample.tar.gz)

**Comment by erikrose** [comment]
Confirmed: I get the weird tags when running your archived example. I'll put it on my list of things to dig into. Thanks for reporting!

**Comment by erikrose** [comment]
Upon a tingling of insight, I tried removing one line from your `.jsdoc.json` conf file:

`"plugins": [ "plugins/markdown" ],`

That was all it took. Apparently, the markdown plugin makes `jsdoc -X` emit HTML output rather than its usual plain text. If you're continuing to use jsdoc by itself as well, I recommend making a second jsdoc conf file for sphinx-js to reference. But really, all you seem to be using it for is the `recurse` option, so you may find it simpler to specify more than one `js_source_path` instead.

**Comment by jthomerson** [comment]
Thanks @erikrose!
