### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by erikrose** [erikrose/sphinx-js#37]
Some things are different on Windows. Here I'm collecting a list of them and mitigations to implement. Some of this is from https://bugzilla.mozilla.org/show_bug.cgi?id=1232403, where we use sphinx-js on mozilla-central.

* At https://github.com/erikrose/sphinx-js/blob/7ba9bf1d111b14bae85a1e16c143aa6ee5147d4e/sphinx_js/jsdoc.py#L24, we should call `jsdoc.cmd`, not just `jsdoc`, if the platform is Windows.
* > It [doesn't hang] if we change the previous line to |p = Popen(jsdoc_command, stdout=temp)|, i.e. removing |stderr=PIPE|.

    I can't think of a good reason to have stderr=PIPE there. Letting it default to None, as you're doing, should be fine, with the additional possible advantage that you can see jsdoc's error output, if any. (I'm not sure where the PIPE output ends up if we don't read and explicitly print it--probably not onscreen.)

**Comment by FoxNeo** [comment]
Is this change on the last release version? https://pypi.python.org/pypi/sphinx-js/2.3

**Comment by erikrose** [comment]
It is now! Just released 2.3.1: https://pypi.python.org/pypi/sphinx-js/.

**Comment by FoxNeo** [comment]
Thanks @erikrose
