### ISSUE TITLE
Support for @example?

### ISSUE THREAD

**Issue by lidavidm** [erikrose/sphinx-js#41]
Would you be opposed to supporting the [@example tag](http://usejsdoc.org/tags-example.html)? I took a quick look at it (since I'd like to keep as much inline in JS as possible, rather than in rST) and it seems fairly simple - simply read `examples` from the doclet in `_template_vars` and then extend the rST template.

**Comment by erikrose** [comment]
I have nothing against it! Want to open a PR?
