### ISSUE TITLE
Path resolution issue on Windows

### ISSUE THREAD

**Issue by flozz** [erikrose/sphinx-js#47]
Hello,

I have an issue for building a doc on Windows using sphin-js (it works on Linux and probably on Mac OS too).

Here is an example that will cause issue on Windows:

```rst
.. jsdoc:autoclass:: foo/bar/baz.Baz
```

Trying to build it on Windows:

```
$ make html
[...]
No JSDoc documentation was found for object "foo/bar/baz.Baz" or any path ending with that.
```
The problem is that Windows uses  `"\"` as path separator instead of `"/"`, so jsdoc reports paths like `"C:\...\foo\bar\baz.js"` in its JSON and sphinx-js does not handle this (it mixes both slashes and backslashes in the paths).

I made a quick fix (hack?) to allow my team to workaround this issue: https://github.com/flozz/sphinx-js/commit/c3471e3ef9af34ef7b91bf09c7928b4e14c63f6a but I do not know if I should PR it on this project or if we must find a better way to handle backslash on Windows...

:)

**Comment by erikrose** [comment]
I think you've made the patch in the right place, but we should probably be calling some path-splitting routine in the `os` or `os.path` module to cover all the corner cases. (On a non-Windows system, a filename might contain a backslash and throw everything off.) Let's see which of us gets around to fixing it first. :-)

**Comment by flozz** [comment]
I could not find any path-splitting method in the `os.path` module, but there is an `os.path.sep` attribute that gives the path separator of the OS, so it can be used to split the path, and then we can rebuild it using slashes.

I wrote this here: https://github.com/flozz/sphinx-js/commit/09c50b8a11af01a957d318a1e06077b511d08f45 but I have not tested it yet as I have no Windows PC... I will test this Monday and make a PR if it works :)
