### ISSUE TITLE
Missing parameters when using es6 object destructuration in parameters

### ISSUE THREAD

**Issue by flozz** [erikrose/sphinx-js#49]
Hello,

I have an issue to document a function that uses object destructuration in the parameters:

```javascript
/**
 * @param foo
 * @param {Object} params
 * @param params.bar
 * @param params.baz
 */
function example(foo, { bar, baz }) {
    // ...
}
```

Output with sphinx-js:

![capture d ecran de 2018-03-20 10-44-38](https://user-images.githubusercontent.com/971438/37647466-9a0544a2-2c2c-11e8-840f-16fe7446ffd4.png)

Output with jsodc:

![capture d ecran de 2018-03-20 10-45-41](https://user-images.githubusercontent.com/971438/37647479-a01201d2-2c2c-11e8-9f3c-4c0b7e66bff0.png)

When using destructuration, the JSON outputted by jsodc looks like this:

```javascript
[
    {
        // ...
        "meta": {
            // ...
            "code": {
                // ...
                "paramnames": [
                    "foo",
                    ""
                ]
            }
        },
        "params": [
            {
                "name": "foo"
            },
            {
                "type": {
                    "names": [
                        "Object"
                    ]
                },
                "name": "params"
            },
            {
                "name": "params.bar"
            },
            {
                "name": "params.baz"
            }
        ],
        "name": "example",
        "longname": "example",
        "kind": "function",
        "scope": "global"
    },
    // ...
]
```

As [sphinx-js relies on the `paramnames`](https://github.com/erikrose/sphinx-js/blob/master/sphinx_js/renderers.py#L109) to generate the function signature, it is not able to display the destructured parameters.

Do you think that we can use the `params` section of the doclet instead of `meta.code.paramnames`?

**Comment by erikrose** [comment]
I don't see why not! I'd be happy to accept a patch toward this, as I have the same situation myself in several places. If there is a reason not to, I'm sure it will become clear during work on the patch.
