### ISSUE TITLE
Install sphinx

### ISSUE THREAD

**Issue by brianlane** [erikrose/sphinx-js#54]
Subject: I'm trying to install sphinx to later use with a Dockerfile

Problem
Here is the problem received from npm run docs:
Running Sphinx v1.7.2
loading pickled environment... failed: unsupported pickle protocol: 4

Exception occurred:
File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory

Procedure to reproduce the problem
wget https://github.com/veg/phylotree.js/archive/master.zip
unzip master.zip
cd phylotree.js-master/
pip install -r requirements.txt
npm run docs

Error logs / results
cat /phylotree.js-master/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'docs' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'predocs', 'docs', 'postdocs' ]
5 info lifecycle phylotree@0.1.6predocs: phylotree@0.1.6
6 silly lifecycle phylotree@0.1.6predocs: no script for predocs, continuing
7 info lifecycle phylotree@0.1.6docs: phylotree@0.1.6
8 verbose lifecycle phylotree@0.1.6docs: unsafe-perm in lifecycle true
9 verbose lifecycle phylotree@0.1.6docs: PATH: /usr/share/npm/bin/node-gyp-bin:/phylotree.js-master/node_modules/.bin:/phylotree.js-master/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle phylotree@0.1.6docs: CWD: /phylotree.js-master
11 silly lifecycle phylotree@0.1.6docs: Args: [ '-c', 'sphinx-build -b html docs documentation' ]
12 silly lifecycle phylotree@0.1.6docs: Returned: code: 2 signal: null
13 info lifecycle phylotree@0.1.6~docs: Failed to exec docs script
14 verbose stack Error: phylotree@0.1.6 docs: sphinx-build -b html docs documentation
14 verbose stack Exit status 2
14 verbose stack at EventEmitter. (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack at emitTwo (events.js:87:13)
14 verbose stack at EventEmitter.emit (events.js:172:7)
14 verbose stack at ChildProcess. (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack at emitTwo (events.js:87:13)
14 verbose stack at ChildProcess.emit (events.js:172:7)
14 verbose stack at maybeClose (internal/child_process.js:821:16)
14 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid phylotree@0.1.6
16 verbose cwd /phylotree.js-master
17 error Linux 4.4.0-116-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "docs"
19 error node v4.2.6
20 error npm v3.5.2
21 error code ELIFECYCLE
22 error phylotree@0.1.6 docs: sphinx-build -b html docs documentation
22 error Exit status 2
23 error Failed at the phylotree@0.1.6 docs script 'sphinx-build -b html docs documentation'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the phylotree package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error sphinx-build -b html docs documentation
23 error You can get information on how to open an issue for this project with:
23 error npm bugs phylotree
23 error Or if that isn't available, you can get their info via:
23 error npm owner ls phylotree
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

Expected results
Should have installed the docs successfully

Reproducible project / your project
This was preformed in the root directory as root in a virtual environment - atmosphere

Environment info
OS: Ubuntu 16.04 GUI XFCE Base v2.1

Here is the full traceback:

root@vm142-57:/# cat /tmp/sphinx-err-TlLriM.log
# Sphinx version: 1.7.2
# Python version: 2.7.12 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 233, in __init__
    self._init_builder()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 311, in _init_builder
    self.emit('builder-inited')
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 444, in emit
    return self.events.emit(event, self, *args)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/usr/local/lib/python2.7/dist-packages/sphinx_js/jsdoc.py", line 31, in run_jsdoc
    p = Popen(jsdoc_command, stdout=temp, stderr=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

I have already posted this in the sphinx git discussion and their response was this:

It seems the error is raised from sphinx_js. I guess jsdoc is required to run it.

  File "/usr/local/lib/python2.7/dist-packages/sphinx_js/jsdoc.py", line 31, in run_jsdoc
    p = Popen(jsdoc_command, stdout=temp, stderr=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
Anyway, this is a bug of sphinx_js. Please report this to their project.

Any help would be greatly appreciated!

**Comment by brianlane** [comment]
I used the command provided and also npm install -g express but I still receive the same traceback


root@vm142-73:/phylotree.js-master# npm run docs

> phylotree@0.1.6 docs /phylotree.js-master
> sphinx-build -b html docs documentation

Running Sphinx v1.7.2
loading pickled environment... failed: unsupported pickle protocol: 4

Sphinx error:
jsdoc found no JS files in the directories ['/phylotree.js-master']. Make sure js_source_path is set correctly in conf.py. It is also possible (though unlikely) that jsdoc emitted invalid JSON.

npm ERR! Linux 4.4.0-116-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "docs"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! phylotree@0.1.6 docs: `sphinx-build -b html docs documentation`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the phylotree@0.1.6 docs script 'sphinx-build -b html docs documentation'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phylotree package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     sphinx-build -b html docs documentation
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phylotree
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phylotree
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /phylotree.js-master/npm-debug.log
root@vm142-73:/phylotree.js-master# sphinx-build -b html docs documentation
Running Sphinx v1.7.2
loading pickled environment... failed: unsupported pickle protocol: 4

Exception occurred:
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
The full traceback has been saved in /tmp/sphinx-err-WDrHsF.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
root@vm142-73:/phylotree.js-master# cat /tmp/sphinx-err-WDrHsF.log
# Sphinx version: 1.7.2
# Python version: 2.7.12 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 233, in __init__
    self._init_builder()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 311, in _init_builder
    self.emit('builder-inited')
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 444, in emit
    return self.events.emit(event, self, *args)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/usr/local/lib/python2.7/dist-packages/sphinx_js/jsdoc.py", line 31, in run_jsdoc
    p = Popen(jsdoc_command, stdout=temp, stderr=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by erikrose** [comment]
I'm not sure quite what to make of your error. It looks like you're getting 2. First, you see "jsdoc found no JS files in the directories". That implies it's actually finding `jsdoc` now, as that error happens only after successfully running it. But later, you paste "OSError: [Errno 2] No such file or directory". Is that still coming out, too?

Do you in fact have JS source code in /phylotree.js-master? What happens if you go in there and run `jsdoc -X .` on the command line?

**Comment by brianlane** [comment]
root@vm142-73:/phylotree.js-master# jsdoc -X .
An argument like -d=<directory> or --directory=<directory> is mandatory!
Try 'jsdoc --help' or 'man jsdoc' for more information.
root@vm142-73:/phylotree.js-master# jsdoc -X -d=.
java -Djsdoc.template.dir=/usr/share/jsdoc-toolkit/templates/jsdoc -jar /usr/share/java/jsrun.jar /usr/share/jsdoc-toolkit/app/run.js -X -d=.
>> WARNING: No source files to work on. Nothing to do.

**Comment by erikrose** [comment]
I can't reproduce the error you're seeing. I see 2 possible explanations:

1. You're using a different (much, much older?) version of jsdoc than me. What does `jsdoc --version` say for you? I'm using 3.5.5.
2. You're apparently using a Java-based implementation of JS rather than node.js. There could be some difference in the handling of commandline args. Is it feasible for you to try again with node.js?

**Comment by brianlane** [comment]
When I try: jsdoc --version

I get this:
An argument like -d=<directory> or --directory=<directory> is mandatory!
Try 'jsdoc --help' or 'man jsdoc' for more information.

Is there another way to see the version?

**Comment by erikrose** [comment]
I'm afraid you've just demonstrated that something is wonky with your jsdoc installation. That's the root problem. I recommend getting a fresh copy of node.js and reinstalling jsdoc using `npm install jsdoc`.

**Comment by brianlane** [comment]
Just an fyi, I never had node.js installed at all (I think that was the issue). Now I have this output for npm run docs:

phylotree@0.1.6 docs /phylotree.js-master
> sphinx-build -b html docs documentation

Running Sphinx v1.7.2
loading pickled environment... failed: unsupported pickle protocol: 4
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 8 source files that are out of date
updating environment: 8 added, 0 changed, 0 removed
phylotree.js:d3.layout.newick_parser(16):8: (ERROR/3) Unexpected indentation.            
reading sources... [100%] advanced                                                      
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] selection                                                      
generating indices... genindex
writing additional pages... search
copying static files... WARNING: html_static_path entry u'/phylotree.js-master/docs/_static' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 1 warnings.

The HTML pages are in documentation.

**Comment by erikrose** [comment]
So glad you got it working!
