### ISSUE TITLE
Error handling when jsdoc not installed

### ISSUE THREAD

**Issue by tk0miya** [erikrose/sphinx-js#55]
As reported at #54, it seems sphinx-js extension raises OSError if `jsdoc` command not found.
Could you catch it and reraise `sphinx.errors.ExtensionError` instead to show better message?
If so, Sphinx will shutdown safely.

Thanks,

**Comment by erikrose** [comment]
Your wish is my command. :-)

**Comment by tk0miya** [comment]
Thanks!
