### ISSUE TITLE
RestructuredText injection in param names

### ISSUE THREAD

**Issue by flozz** [erikrose/sphinx-js#58]
Hello,

I have a small issue when trying to document a parameter called `module_`:

```javascript
/**
 * @param module_
 */
function injection(module_) {}
```
![capture d ecran de 2018-04-05 16-47-22](https://user-images.githubusercontent.com/971438/38373531-cbdba5a8-38f1-11e8-8c95-70c0ca7d2ef3.png)

The underscore is not visible in the arguments list. In fact it is interpreted as RestructuredText syntax, and it is also possible to break the document formating (ok this one should not occur in real-life projects):

```javascript
/**
 * @param :foo
 */
function injection2() {}
```
![capture d ecran de 2018-04-05 16-47-28](https://user-images.githubusercontent.com/971438/38373705-26a20be4-38f2-11e8-8872-d6f6dbea6f9a.png)

Anyway this is not realy a severe problem, I am looking how to fix this :)

**Comment by erikrose** [comment]
Good catch! We'll have to figure out how to escape those. There's probably a routine in docutils or something.

**Comment by flozz** [comment]
I found nothing useful in `docutils.utils` and I aldso found this in the docutils documentation: https://docutils.readthedocs.io/en/sphinx-docs/dev/rst/problems.html#character-escaping-mechanism

It say there is no escape mechanism in RestructuredText... but after some test, it seems backslashes work (maybe it is implemented by sphinx itself or maybe the doc is not up to date?)...

Anyway, I keep digging to find a nice routine somewhere, else I will write one myself :)

**Comment by erikrose** [comment]
Yes, backslash is the canonical escaper. I just assumed there'd be a routine, but who knows? I suppose you could search for "\". :-)
