### ISSUE TITLE
jsdoc working directory

### ISSUE THREAD

**Issue by tkhyn** [erikrose/sphinx-js#78]
Hi and thanks for sphinx-js

When specifying a jsdoc.json file which has excluded directory defined by a relative path, these directories are evaluated from the directory jsdoc is run from, i.e. the directory sphinx-build is run from. This directory may change depending on configurations, and it would therefore be interesting to be able:

- either to specify jsdoc's working directory
- force jsdoc to be run in the conf.py file's directory

The change is relatively trivial (passing a working directory to subprocess.Popen) I'll be happy to create a PR after discussion on what would the best solution be.

**Comment by erikrose** [comment]
Forcing it to be run from conf.py's directory sounds good to me. Then, if we need to make it configurable for some reason in the future, we can. I'll happily accept your PR!

**Comment by erikrose** [comment]
Just released 2.7.1, which includes this fix.
